In [1]:
import numpy as np
import pandas as pd

# 1.二进制数据读写：

In [2]:
df = pd.read_csv("./data/PM25.csv",encoding='gb18030')
df

    城市  超标天数  超标月数  省份 所在区域
0   和田   177  5.90  新疆   西部
1   喀什   163  5.43  新疆   西部
2  石家庄   117  3.90  河北   东部
3  阿克苏   113  3.77  新疆   西部
4   临汾   110  3.67  山西   中部
5   保定   109  3.63  河北   东部
6   咸阳   107  3.57  陕西   中部
7   安阳   104  3.47  河南   中部
8   邢台   103  3.43  河北   东部

In [3]:
# 将数据以pickle格式写入硬盘
df.to_pickle("./data/example_pickle")

In [4]:
# 读取pickle格式文件
pd.read_pickle("./data/example_pickle")

    城市  超标天数  超标月数  省份 所在区域
0   和田   177  5.90  新疆   西部
1   喀什   163  5.43  新疆   西部
2  石家庄   117  3.90  河北   东部
3  阿克苏   113  3.77  新疆   西部
4   临汾   110  3.67  山西   中部
5   保定   109  3.63  河北   东部
6   咸阳   107  3.57  陕西   中部
7   安阳   104  3.47  河南   中部
8   邢台   103  3.43  河北   东部

# 2.excel数据读写：

### 2.1 读取excel文件

#### ExcelFile类

In [5]:
# 使用 pandas.ExcelFile 类来创建一个实例
xlsx = pd.ExcelFile("./data/PM25.xlsx")

In [6]:
# 该对象可以显示文件中可用工作表名称的列表
xlsx.sheet_names

['Sheet1']

In [7]:
# 然后使用 parse 将存储在工作表中的数据读入 DataFrame 中
xlsx.parse(sheet_names="Sheet1")

   Unnamed: 0   城市  超标天数  超标月数  省份 所在区域
0           0   和田   177  5.90  新疆   西部
1           1   喀什   163  5.43  新疆   西部
2           2  石家庄   117  3.90  河北   东部
3           3  阿克苏   113  3.77  新疆   西部
4           4   临汾   110  3.67  山西   中部
5           5   保定   109  3.63  河北   东部
6           6   咸阳   107  3.57  陕西   中部
7           7   安阳   104  3.47  河南   中部
8           8   邢台   103  3.43  河北   东部

In [8]:
# 此时 Excel 表有一个索引列，可以通过 index_col 参数取消
xlsx.parse(sheet_name="Sheet1", index_col=0)

    城市  超标天数  超标月数  省份 所在区域
0   和田   177  5.90  新疆   西部
1   喀什   163  5.43  新疆   西部
2  石家庄   117  3.90  河北   东部
3  阿克苏   113  3.77  新疆   西部
4   临汾   110  3.67  山西   中部
5   保定   109  3.63  河北   东部
6   咸阳   107  3.57  陕西   中部
7   安阳   104  3.47  河南   中部
8   邢台   103  3.43  河北   东部

#### read_excel()

In [9]:
xlsx = pd.read_excel("./data/PM25.xlsx",sheet_name="Sheet1", index_col=0)
xlsx

    城市  超标天数  超标月数  省份 所在区域
0   和田   177  5.90  新疆   西部
1   喀什   163  5.43  新疆   西部
2  石家庄   117  3.90  河北   东部
3  阿克苏   113  3.77  新疆   西部
4   临汾   110  3.67  山西   中部
5   保定   109  3.63  河北   东部
6   咸阳   107  3.57  陕西   中部
7   安阳   104  3.47  河南   中部
8   邢台   103  3.43  河北   东部

### 2.2 写入excel文件

#### ExcelWriter类

In [10]:
writer = pd.ExcelWriter("./data/PM25.xlsx")
df.to_excel(writer,"Sheet1")
writer.save()

#### to_excel()

In [11]:
df.to_excel('./data/PM25.xlsx')